# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a141b6dcdee3c5afdc0c0445c396f73be59d546f92afc9462b88bd5a2c1d4057f9d135b93e5c6e180f94311552d9e3bebb6dcc88aab8de50b1f17d5c90738bcf

test:
  secret_key_base: 7eb7918bda4d1defdb368537b8c6cd756b546de15cf269b48c3758235f7f90de3460325ce47db693cb847937fbacc3b03f74814f4b4781af1e78d9f3eb3f65a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
